General:
  Prefix_Dir_Enabled: true
  Prefix_Enabled: true
  HandleCmdletError: true
  PrintCmdletDebug: false
  PrintComments: false

SmartInput:
  Enabled: true
  TabCompletion: false
  History: true
  HistoryType: "File" # 'File' or 'Memory'
  HistorySuggest: true
  Highlight: true
  ShowToolBar: false
  MultiLine: false
  MouseSupport: false
  LineWrap : true
  CursorChar: "BLINKING_BEAM" # BLOCK, UNDERLINE, BEAM, BLINKING_BLOCK, BLINKING_UNDERLINE, BLINKING_BEAM

Presets:
  Prefix: '> '
  Title: Crosshell (Zedix)
