attribute_modifiers:
  distance:
    hider_modifier: 1
    seeker_modifier: 1
  ingenuity:
    hider_modifier: -2
    seeker_modifier: -1
  insidiousness:
    hider_modifier: 2
    seeker_modifier: 3
  position:
    hider_modifier: 1
    seeker_modifier: 4
  smell:
    hider_modifier: 1
    seeker_modifier: 2
  sound:
    hider_modifier: -3
    seeker_modifier: 2
missing_attribute_default: 1
players:
  olle:
    attributes:
      distance: 8.3
      ingenuity: 1
      insidiousness: 1
      position: 1
      smell: 1
      sound: 1
    type: ''
  orvar:
    attributes:
      distance: 3
      ingenuity: 10
      insidiousness: 8.5
      position: 9
      smell: 3
      sound: 10
    type: ''
  per:
    attributes:
      distance: 1
      ingenuity: 1.6
      insidiousness: 1
      position: 1
      smell: 9
      sound: 1
    type: ''
  pernilla:
    attributes:
      distance: 2
      ingenuity: 3
      insidiousness: 5
      position: 6
      smell: 9
      sound: 7.0
    type: ''
  stina:
    attributes:
      distance: 5
      ingenuity: 4.2
      insidiousness: 5
      position: 5
      smell: 5
      sound: 5
    type: ''
randomiser_parameters:
  offset_max: 10
  offset_min: 1
  offset_type: ''
seekerfactor_default: 1
